name: Build and Deploy to Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Backup CNAME if exists
        run: |
          if [ -f docs/CNAME ]; then cp docs/CNAME CNAME.bak; fi

      - name: Remove old docs content
        run: |
          rm -rf docs/*
          mkdir -p docs

      - name: Restore CNAME if backup exists
        run: |
          if [ -f CNAME.bak ]; then mv CNAME.bak docs/CNAME; fi

      - name: Copy build output to docs
        run: cp -r dist/* docs/

      - name: Commit and push changes to docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Automated build and deploy to docs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}