name: Build and Deploy to Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Backup CNAME if exists
        run: |
          if [ -f docs/CNAME ]; then cp docs/CNAME CNAME.bak; fi

      - name: Remove old
